### ISSUE TITLE
您好，请问您的声卡驱动正常么？

### ISSUE THREAD

**Issue by yyfn** [haos001/XPS13-9343-Clover#1]
我也是xps13 9343，现在是windows，曾经用的是apolealc驱动声卡，当注入3的时候没有麦克风，注入13的时候有麦克风，但是声音会慢慢变得特别奇怪，除非手动更改一下音量触发系统的“咚”一声才会正常。
请问您有这个问题么？

**Comment by haos001** [comment]
@yyfn  Yes, I have this problem. How you change volume trigger? I don't understand Chinese, please response in English

**Comment by yyfn** [comment]
I am currently using node 3, the speakers are normal, but there is no microphone.
I remember that it seems that I used the 10.12 counterfeit driver from others to use the speaker and microphone normally, but on the 10.14 system, the sound became especially strange.

http://bbs.pcbeta.com/forum.php?mod=viewthread&tid=1754764&highlight=9343

[AppleHDA.kext.zip](https://github.com/haos001/XPS13-9343-Clover/files/2599942/AppleHDA.kext.zip)

**Comment by haos001** [comment]
I have all the same, use node 3 too. Did not found a solution. If you find a solution please text me.

**Comment by yyfn** [comment]
OK~👌

**Comment by yyfn** [comment]
This is my clover config, you can use Apple's touchpad gesture.
[EFI-9343.zip](https://github.com/haos001/XPS13-9343-Clover/files/2602604/EFI-9343.zip)

**Comment by yyfn** [comment]
[AppleALC.kext.zip](https://github.com/haos001/XPS13-9343-Clover/files/2612069/AppleALC.kext.zip)

layout-id:23 
I reproduced the driver and submitted it to Applealc, which will be built-in in the next version without any surprise.

**Comment by haos001** [comment]
@yyfn With this kext mic and speakers work good?

**Comment by yyfn** [comment]
> @yyfn With this kext mic and speakers work good?

yes

**Comment by yyfn** [comment]
Is this useful for your computer?

**Comment by vantuan88291** [comment]
> This is my clover config, you can use Apple's touchpad gesture.
> [EFI-9343.zip](https://github.com/haos001/XPS13-9343-Clover/files/2602604/EFI-9343.zip)

hi, i used this clover and get work perfect with 10.14.6, but still no sound from 10.14.3, can you share me how to fix? or your clover now? thanks, i use dell xps 13 9343 too

**Comment by vantuan88291** [comment]
wow, i am using your clover but no sound, everything perfec. But after i use VoodooHDA the sound is perfect, mic, headphone, speaker very good

**Comment by vantuan88291** [comment]
this is my clover: https://github.com/vantuan88291/clover-xps13-9343
