### ISSUE TITLE
what's your computer's spec?

### ISSUE THREAD

**Issue by dukelyuu** [haos001/XPS13-9343-Clover#2]
what's your computer's spec?
mine is 
CPU:I7-5500U
intel HD5500 display
4K QHD screen

and i cant start install from the macOS Mojave

**Comment by haos001** [comment]
Hi! 
My specs

Dell XPS 13 2015
CPU - i5 5500U
Video - Intel HD5500
Display - 4K QHD screen

**Comment by dukelyuu** [comment]
> 
> 
> Hi!
> My specs
> 
> Dell XPS 13 2015
> CPU - i5 5500U
> Video - Intel HD5500
> Displa - 4K QHD screen

thx...
